### ISSUE TITLE
[JHSD] Add history of all Sikh Gurus and prominent Sikhs

### ISSUE THREAD

**Issue by bogas04** [jujhars13/my-website#1]
Why not ? :smile: 

* [ ] Guru Angad Dev Ji
* [ ] Guru Raam Daas Ji
* [ ] Guru Hari Krishan Ji

---

* [ ] Bhai Mardana Ji
* [ ] Baba Budda Ji
* [ ] Bhai Gurdas Ji
* [ ] Bhai NandLaal Ji
* [ ] Bhatts
* [ ] Baba Deep Ji
* [ ] Bade Sahibzaade

**Comment by jujhars13** [comment]
Because the student's on this course have already covered that in their core curriculem.  I've got about 45 mins to present and they know nothing about the rest of Sikh history.

I'm happy for you to fork this and add other stuff in, but for this particular course timing it wouldn't work : http://journeyintotheheartofsikhdharma.org/

**Comment by bogas04** [comment]
Oh! I thought this was a random website about Sikhi History. Turns out it's much more than that and that's awesome 👍 

Let's see where #2 leads this into.
